name: Dependent job

on: push

jobs:
  job_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: date

  job_on_windows:
    name: A windows job
    runs-on: windows-latest
    steps:
      - name: First step in windows job
        run: date

  job_on_macos:
    name: A job on Mac after first two jobs
    needs: [job_on_ubuntu, job_on_windows]
    runs-on: macos-latest
    steps:
      - run: pwd
      - name: New step
        run: ls
      - name: Third step
        run: env

  final_job:
    name: A final job
    needs: job_on_macos
    runs-on: macos-latest
    steps:
      - run: echo "hello world"
